In [1]:
import pandas as pd

In [2]:
file_path = '/Users/jzavaleta/Desktop/portafolio-data-analytics/01_Football/1_Data/wc_Mexico.csv'
df = pd.read_csv(file_path)

/var/folders/gw/86r3m8ps639925ypmvdrzd2jzj0v0f/T/ipykernel_61280/1832625329.py:2: DtypeWarning: Columns (0: clearance_body_part, 1: clearance_head, 2: clearance_left_foot, 3: clearance_other, 4: clearance_right_foot, 5: foul_committed_offensive, 6: foul_committed_penalty, 7: foul_won_penalty, 8: injury_stoppage_in_chain, 9: miscontrol_aerial_won, 10: off_camera, 11: out, 12: pass_inswinging, 13: pass_outswinging, 14: goalkeeper_punched_out, 15: pass_cut_back, 16: pass_no_touch, 17: dribble_no_touch, 18: pass_miscommunication, 19: bad_behaviour_card, 20: ball_recovery_offensive, 21: block_offensive, 22: pass_backheel, 23: shot_open_goal, 24: shot_redirect) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [3]:
# Vista previa de las primeras y últimas filas
df.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,pass_no_touch,shot_deflected,dribble_no_touch,pass_miscommunication,bad_behaviour_card,ball_recovery_offensive,block_offensive,pass_backheel,shot_open_goal,shot_redirect
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.tail()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,pass_no_touch,shot_deflected,dribble_no_touch,pass_miscommunication,bad_behaviour_card,ball_recovery_offensive,block_offensive,pass_backheel,shot_open_goal,shot_redirect
22681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Verificación de filas exactamente duplicadas
print(f"Filas duplicadas: {df.duplicated().sum()}")

Filas duplicadas: 0

In [6]:
# Dimensiones del DataFrame (filas, columnas)
print(df.shape)

(22686, 105)

In [7]:
# Información general de columnas, tipos de datos y memoria usada
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22686 entries, 0 to 22685
Columns: 105 entries, 50_50 to shot_redirect
dtypes: float64(8), int64(8), object(44), str(45)
memory usage: 23.4+ MB

In [8]:
# Porcentaje de nulos por columna
porcentaje_nulos = (
    ((df.isnull().sum() / len(df)) * 100)
    .sort_values(ascending=True)
    .to_frame(name='% Nulos')
)

porcentaje_nulos

                          % Nulos
id                       0.000000
index                    0.000000
minute                   0.000000
play_pattern             0.000000
period                   0.000000
...                           ...
shot_redirect           99.991184
clearance_other         99.995592
goalkeeper_punched_out  99.995592
bad_behaviour_card      99.995592
dribble_no_touch        99.995592

[105 rows x 1 columns]