In [12]:
import pandas as pd

In [13]:
file_path = '/Users/jzavaleta/Desktop/portafolio-data-analytics/01_Football/1_Data/wc_Mexico.csv'
df = pd.read_csv(file_path)

/var/folders/gw/86r3m8ps639925ypmvdrzd2jzj0v0f/T/ipykernel_2066/1832625329.py:2: DtypeWarning: Columns (0: clearance_body_part, 1: clearance_head, 2: clearance_left_foot, 3: clearance_other, 4: clearance_right_foot, 5: foul_committed_offensive, 6: foul_committed_penalty, 7: foul_won_penalty, 8: injury_stoppage_in_chain, 9: miscontrol_aerial_won, 10: off_camera, 11: out, 12: pass_inswinging, 13: pass_outswinging, 14: goalkeeper_punched_out, 15: pass_cut_back, 16: pass_no_touch, 17: dribble_no_touch, 18: pass_miscommunication, 19: bad_behaviour_card, 20: ball_recovery_offensive, 21: block_offensive, 22: pass_backheel, 23: shot_open_goal, 24: shot_redirect) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

In [14]:
# Vista previa de las primeras y últimas filas
df.head()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,pass_no_touch,shot_deflected,dribble_no_touch,pass_miscommunication,bad_behaviour_card,ball_recovery_offensive,block_offensive,pass_backheel,shot_open_goal,shot_redirect
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.tail()

,50_50,ball_receipt_outcome,ball_recovery_recovery_failure,block_deflection,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_other,...,pass_no_touch,shot_deflected,dribble_no_touch,pass_miscommunication,bad_behaviour_card,ball_recovery_offensive,block_offensive,pass_backheel,shot_open_goal,shot_redirect
22681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22683,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# Verificación de filas exactamente duplicadas
print(f"Filas duplicadas: {df.duplicated().sum()}")

Filas duplicadas: 0

In [17]:
# Dimensiones del DataFrame (filas, columnas)
print(df.shape)

(22686, 106)

In [18]:
# Información general de columnas, tipos de datos y memoria usada
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 22686 entries, 0 to 22685
Columns: 106 entries, 50_50 to shot_redirect
dtypes: float64(8), int64(8), object(44), str(46)
memory usage: 23.6+ MB

In [19]:
# Porcentaje de nulos por columna
porcentaje_nulos = (
    ((df.isnull().sum() / len(df)) * 100)
    .sort_values(ascending=True)
    .to_frame(name='% Nulos')
)

porcentaje_nulos

                          % Nulos
id                       0.000000
index                    0.000000
minute                   0.000000
play_pattern             0.000000
period                   0.000000
...                           ...
foul_committed_penalty  99.991184
clearance_other         99.995592
goalkeeper_punched_out  99.995592
bad_behaviour_card      99.995592
dribble_no_touch        99.995592

[106 rows x 1 columns]

In [21]:
# Cruce directo de 'type' contra 'competencia'
events = pd.crosstab(df['type'], df['competencia']).reset_index()

# Renombramos el nombre del índice de columnas si es necesario
events.columns.name = None

events['Total'] = events['wc_18'] + events['wc_22']

events = events.sort_values(by='Total', ascending=False).reset_index(drop=True)

events

                 type  wc_18  wc_22  Total
0                Pass   3399   2686   6085
1       Ball Receipt*   3180   2447   5627
2               Carry   2977   1985   4962
3            Pressure   1507    755   2262
4       Ball Recovery    332    287    619
5                Duel    203    222    425
6               Block    155    119    274
7             Dribble    185     75    260
8           Clearance    102    135    237
9         Goal Keeper    155     82    237
10     Foul Committed    123    104    227
11           Foul Won    113     99    212
12               Shot    139     62    201
13      Dribbled Past    127     45    172
14         Miscontrol     73     89    162
15       Dispossessed     80     74    154
16       Interception     78     67    145
17          Camera On    134      0    134
18    Injury Stoppage     19     31     50
19       Substitution     24     24     48
20     Tactical Shift     17     13     30
21           Half End     16     12     28
22         Half Start     16     12     28
23         Camera off     28      0     28
24              50/50     10     15     25
25        Starting XI      8      6     14
26  Referee Ball-Drop      2      8     10
27             Shield      2      6      8
28          Player On      1      5      6
29         Player Off      1      5      6
30            Offside      3      1      4
31              Error      3      0      3
32      Bad Behaviour      1      0      1
33   Own Goal Against      1      0      1
34       Own Goal For      1      0      1